"""ReplyPlan Builder (SHEEP-307).

Builds a structured ReplyPlan from ConversationEngine output and ContextEnvelope.

Governance basis:
- Master §5: AI output must be structured and governed.
- DEC-SHEEP-306: ReplyPlan is the canonical AI output format.
- REPLY_AND_ACTION_SAFETY: AI confidence alone never grants execution permission.

Key invariants:
- AI output is a plan, not execution authority.
- Facts, knowledge, and inference are structurally distinguished.
- AI inference MUST NOT silently become an authoritative fact.
- Verification requirements are explicit.
- Policy metadata governs execution path.
- MVP: rollout_mode defaults to "HUMAN_CONFIRM" (safe default).

Usage:
    builder = ReplyPlanBuilder()
    plan = builder.build(
        envelope=context_envelope,
        reply="我们会在48小时内发货",
        facts_used=[...],
        knowledge_used=[...],
        inferences_used=[...],
    )
"""
from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional


class ReplyPlanBuilder:
    """Builds a structured ReplyPlan from ConversationEngine output.
    
    This builder takes the output from ConversationEngine (reply text, trace, etc.)
    and the input ContextEnvelope, and constructs a ReplyPlan that:
    - References the source envelope
    - Inherits identity_lock, scene, trigger_message from envelope
    - Structures reply_content with text, language, segments
    - Builds fact_references, knowledge_references, inference_references
    - Specifies verification_requirements
    - Includes policy_metadata (rollout_mode, confirmation requirements)
    - Lists unknowns that affect execution authorization
    
    MVP Safety:
    - rollout_mode defaults to "HUMAN_CONFIRM" (safe default)
    - requires_confirmation defaults to True
    - This ensures AI output cannot auto-execute without human approval
    """
    
    def __init__(self) -> None:
        """Initialize ReplyPlanBuilder."""
        pass
    
    def build(
        self,
        envelope: Dict[str, Any],
        reply: str,
        facts_used: Optional[List[Dict[str, Any]]] = None,
        knowledge_used: Optional[List[Dict[str, Any]]] = None,
        inferences_used: Optional[List[Dict[str, Any]]] = None,
        segments: Optional[List[Dict[str, Any]]] = None,
        unknowns: Optional[List[Dict[str, Any]]] = None,
        policy_decision: Optional[Dict[str, Any]] = None,  # SHEEP-308: External policy evaluation
    ) -> Dict[str, Any]:
        """Build a ReplyPlan from envelope and conversation output.
        
        Args:
            envelope: ContextEnvelope dict (input to ConversationEngine)
            reply: Reply text generated by ConversationEngine
            facts_used: List of facts referenced in the reply (from authoritative_facts)
            knowledge_used: List of knowledge entries referenced in the reply
            inferences_used: List of AI inferences used in the reply
            segments: Optional reply segments (structured reply parts)
            unknowns: Optional unknowns that affect execution authorization
            policy_decision: Optional PolicyDecision from PolicyEngine (SHEEP-308).
                If provided, policy_metadata is built from this decision.
                If not provided, defaults to safe HUMAN_CONFIRM (backward compatible).
        
        Returns:
            ReplyPlan dict conforming to reply-plan.schema.json
        
        Example:
            >>> builder = ReplyPlanBuilder()
            >>> plan = builder.build(
            ...     envelope={"envelope_id": "...", "identity_lock": {...}, ...},
            ...     reply="我们会在48小时内发货",
            ...     facts_used=[{"fact_key": "shop_facts.shipping_policy", ...}],
            ...     knowledge_used=[{"knowledge_id": "...", "relevance_score": 0.95}],
            ... )
            >>> plan["plan_id"]
            '...'
            >>> plan["reply_content"]["text"]
            '我们会在48小时内发货'
        """
        # Generate unique plan ID
        plan_id = str(uuid.uuid4())
        
        # Reference to source envelope
        envelope_ref = envelope.get("envelope_id", "")
        
        # Inherit identity_lock, scene, trigger_message from envelope
        identity_lock = envelope.get("identity_lock", {})
        scene = envelope.get("scene", "UNKNOWN")
        trigger_message = envelope.get("trigger_message", {})
        
        # Build reply_content
        reply_content = self._build_reply_content(reply, segments)
        
        # Build references
        fact_references = self._build_fact_references(facts_used or [])
        knowledge_references = self._build_knowledge_references(knowledge_used or [])
        inference_references = self._build_inference_references(inferences_used or [])
        
        # Build verification_requirements
        verification_requirements = self._build_verification_requirements(envelope)
        
        # Build policy_metadata (SHEEP-308: use external policy_decision if available)
        policy_metadata = self._build_policy_metadata(policy_decision)
        
        # Build unknowns (if any)
        plan_unknowns = self._build_unknowns(unknowns or [])
        
        # Assemble ReplyPlan
        plan: Dict[str, Any] = {
            "plan_id": plan_id,
            "envelope_ref": envelope_ref,
            "identity_lock": identity_lock,
            "scene": scene,
            "trigger_message": trigger_message,
            "reply_content": reply_content,
            "verification_requirements": verification_requirements,
            "created_at": datetime.now(timezone.utc).isoformat(),
        }
        
        # Add optional fields if non-empty
        if fact_references:
            plan["fact_references"] = fact_references
        if knowledge_references:
            plan["knowledge_references"] = knowledge_references
        if inference_references:
            plan["inference_references"] = inference_references
        if policy_metadata:
            plan["policy_metadata"] = policy_metadata
        if plan_unknowns:
            plan["unknowns"] = plan_unknowns
        
        return plan
    
    def _build_reply_content(
        self,
        reply: str,
        segments: Optional[List[Dict[str, Any]]] = None,
    ) -> Dict[str, Any]:
        """Build reply_content structure.
        
        Args:
            reply: Reply text
            segments: Optional reply segments
        
        Returns:
            ReplyContent dict with text, language, and optional segments
        """
        content: Dict[str, Any] = {
            "text": reply,
            "language": "zh-CN",  # Default language for PDD
        }
        
        if segments:
            # Normalize segments to match schema
            normalized_segments = []
            for seg in segments:
                normalized_seg = {
                    "segment_type": seg.get("segment_type", "text"),
                    "content": seg.get("content", ""),
                }
                if "fact_refs" in seg:
                    normalized_seg["fact_refs"] = seg["fact_refs"]
                if "knowledge_refs" in seg:
                    normalized_seg["knowledge_refs"] = seg["knowledge_refs"]
                normalized_segments.append(normalized_seg)
            content["segments"] = normalized_segments
        
        return content
    
    def _build_fact_references(
        self,
        facts_used: List[Dict[str, Any]],
    ) -> List[Dict[str, Any]]:
        """Build fact_references from facts_used.
        
        Args:
            facts_used: List of facts referenced in the reply
        
        Returns:
            List of FactReference dicts
        """
        references = []
        for i, fact in enumerate(facts_used):
            ref = {
                "fact_id": fact.get("fact_id", f"fact_{i}"),
                "fact_key": fact.get("fact_key", ""),
                "source": fact.get("source", "merchant_config"),
            }
            if "value_snapshot" in fact:
                ref["value_snapshot"] = fact["value_snapshot"]
            if "retrieved_at" in fact:
                ref["retrieved_at"] = fact["retrieved_at"]
            references.append(ref)
        return references
    
    def _build_knowledge_references(
        self,
        knowledge_used: List[Dict[str, Any]],
    ) -> List[Dict[str, Any]]:
        """Build knowledge_references from knowledge_used.
        
        Args:
            knowledge_used: List of knowledge entries referenced in the reply
        
        Returns:
            List of KnowledgeReference dicts
        """
        references = []
        for knowledge in knowledge_used:
            ref = {
                "knowledge_id": knowledge.get("knowledge_id", ""),
                "knowledge_type": knowledge.get("knowledge_type", "STORE_RULE"),
                "relevance_score": float(knowledge.get("relevance_score", 0.0)),
            }
            if "store_knowledge_type" in knowledge:
                ref["store_knowledge_type"] = knowledge["store_knowledge_type"]
            if "title" in knowledge:
                ref["title"] = knowledge["title"]
            if "content_snapshot" in knowledge:
                ref["content_snapshot"] = knowledge["content_snapshot"]
            references.append(ref)
        return references
    
    def _build_inference_references(
        self,
        inferences_used: List[Dict[str, Any]],
    ) -> List[Dict[str, Any]]:
        """Build inference_references from inferences_used.
        
        Args:
            inferences_used: List of AI inferences used in the reply
        
        Returns:
            List of InferenceReference dicts
        """
        references = []
        for inference in inferences_used:
            ref = {
                "inference_id": inference.get("inference_id", ""),
                "inference_type": inference.get("inference_type", "intent_classification"),
                "description": inference.get("description", ""),
                "confidence": float(inference.get("confidence", 0.0)),
            }
            if "based_on" in inference:
                ref["based_on"] = inference["based_on"]
            references.append(ref)
        return references
    
    def _build_verification_requirements(
        self,
        envelope: Dict[str, Any],
    ) -> Dict[str, Any]:
        """Build verification_requirements.
        
        MVP: Basic verification requirements.
        Future: More sophisticated verification based on scene, facts, etc.
        
        Args:
            envelope: ContextEnvelope dict
        
        Returns:
            VerificationRequirements dict
        """
        # Check if identity_lock is present and valid
        identity_lock = envelope.get("identity_lock", {})
        identity_lock_valid = bool(
            identity_lock.get("merchant_id")
            and identity_lock.get("store_id")
            and identity_lock.get("platform")
            and identity_lock.get("customer_identity")
        )
        
        # Check if facts are present
        facts = envelope.get("authoritative_facts", {})
        facts_validated = bool(facts)
        
        requirements: Dict[str, Any] = {
            "identity_lock_valid": identity_lock_valid,
            "facts_validated": facts_validated,
        }
        
        # Add required_verifications list
        required_verifications = []
        
        if not identity_lock_valid:
            required_verifications.append({
                "verification_id": "verify_identity_lock",
                "category": "identity_lock",
                "description": "IdentityLock must be complete and valid",
                "blocking": True,
            })
        
        if not facts_validated:
            required_verifications.append({
                "verification_id": "verify_facts",
                "category": "fact_freshness",
                "description": "Authoritative facts must be present and fresh",
                "blocking": True,
            })
        
        if required_verifications:
            requirements["required_verifications"] = required_verifications
        
        return requirements
    
    def _build_policy_metadata(
        self,
        policy_decision: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """Build policy_metadata.
        
        SHEEP-308: Uses external PolicyDecision if provided.
        Falls back to safe defaults (HUMAN_CONFIRM) for backward compatibility.
        
        Args:
            policy_decision: Optional PolicyDecision from PolicyEngine.
                Contains: rollout_mode, requires_confirmation, confirmation_reason,
                reasons, warnings, blocking_issues, evaluated_at, policy_version.
        
        Returns:
            PolicyMetadata dict
        
        Example:
            >>> builder._build_policy_metadata()
            {'rollout_mode': 'HUMAN_CONFIRM', 'requires_confirmation': True, ...}
            >>> builder._build_policy_metadata({'rollout_mode': 'SHADOW', ...})
            {'rollout_mode': 'SHADOW', 'requires_confirmation': False, ...}
        """
        # SHEEP-308: Use external policy decision if available
        if policy_decision is not None:
            rollout_mode = policy_decision.get("rollout_mode", "HUMAN_CONFIRM")
            requires_confirmation = policy_decision.get("requires_confirmation", True)
            confirmation_reason = policy_decision.get(
                "confirmation_reason",
                "Policy requires human confirmation" if requires_confirmation else None
            )
            
            metadata: Dict[str, Any] = {
                "rollout_mode": rollout_mode,
                "requires_confirmation": requires_confirmation,
                "policy_version": policy_decision.get("policy_version", "1.0.0"),
                "evaluated_at": policy_decision.get("evaluated_at", ""),
                "source": "policy_engine",  # SHEEP-308: Indicates dynamic evaluation
            }
            
            if confirmation_reason:
                metadata["confirmation_reason"] = confirmation_reason
            
            # Include evaluation details for audit
            if "reasons" in policy_decision:
                metadata["evaluation_reasons"] = policy_decision["reasons"]
            if "warnings" in policy_decision:
                metadata["evaluation_warnings"] = policy_decision["warnings"]
            if "blocking_issues" in policy_decision:
                metadata["blocking_issues"] = policy_decision["blocking_issues"]
            
            return metadata
        
        # Backward compatible: MVP safe defaults (no policy_decision provided)
        return {
            "rollout_mode": "HUMAN_CONFIRM",  # MVP: safe default
            "requires_confirmation": True,
            "confirmation_reason": "MVP: All AI replies require human confirmation",
            "risk_level": "medium",
            "source": "default",  # Indicates no external policy evaluation
        }
    
    def _build_unknowns(
        self,
        unknowns: List[Dict[str, Any]],
    ) -> List[Dict[str, Any]]:
        """Build unknowns list.
        
        Args:
            unknowns: List of unknowns from envelope or ConversationEngine
        
        Returns:
            List of PlanUnknown dicts
        """
        plan_unknowns = []
        for unknown in unknowns:
            plan_unknown = {
                "unknown_id": unknown.get("unknown_id", ""),
                "category": unknown.get("category", "missing_fact"),
                "description": unknown.get("description", ""),
            }
            if "blocking" in unknown:
                plan_unknown["blocking"] = unknown["blocking"]
            if "mitigation" in unknown:
                plan_unknown["mitigation"] = unknown["mitigation"]
            plan_unknowns.append(plan_unknown)
        return plan_unknowns
